### PR TITLE
Bobbyg603/issue9

### LINKED ISSUE #9: Remove dependency on Fred in e2e tests
Remove the dependency on an event exists on this specific crash/stackKey. The solution is to get a list of crashes and stack keys at test time, pick one, add an event and verify the event was added successfully.

_Originally posted by @bobbyg603 in https://github.com/BugSplat-Git/bugsplat-js-client/pull/7#r643228290_

### PR DESCRIPTION
**Pull request by bobbyg603**
Adds Crash post client and removes dependency on Fred in e2e tests.

TODO

- [x] Fix the tests that failed when switching to bobby_unit_test_db

Fixes #9

### CODE REVIEW

File: src/common/client/s3-api-client/s3-api-client.ts [hunk 1]
```diff
@@ -1,17 +1,18 @@
 import fetchPonyfill from 'fetch-ponyfill';
-import type fs from 'fs';
+import { BugSplatFile } from 'src/common/file/bugsplat-file';
```
Comment (bobbyg603) [inline src/common/client/s3-api-client/s3-api-client.ts:2]: fix path

File: src/post/crash-post-client.ts [hunk 2]
```diff
@@ -0,0 +1,101 @@
...
+
+    private _processorApiClient: BugSplatApiClient;
+    private _s3ApiClient: S3ApiClient;
+
+    constructor(
+        private _database: string,
+        private _environment: Environment = Environment.Node,
+        private _processorIpAddress: string = ''
+    ) {
+        // TODO BG take a something like DatabaseSpecificApiClient instead?
```
Comment (bobbyg603) [inline src/post/crash-post-client.ts:14]: whoops, let's do this

Comment (bobbyg603) [reply src/post/crash-post-client.ts:14]: CrashProcessorClient?

**Comment by bobbyg603** [comment]
Need to add the env variables to the build machine

File: src/post/crash-post-client.ts (hunk 2 above)
Comment (bobbyg603) [inline src/post/crash-post-client.ts:14]: Seems overkill...

File: src/common/file/bugsplat-file.ts [hunk 3]
```diff
@@ -0,0 +1,9 @@
+import type fs from 'fs';
+
+export class BugSplatFile {
```
Comment (bobbyg603) [inline src/common/file/bugsplat-file.ts:3]: Can we do better with the name here?

File: src/post/crash-post-client.ts [hunk 4]
```diff
@@ -0,0 +1,100 @@
...
+        const formData = this._processorApiClient.createFormData();
+        formData.append('database', database);
+        formData.append('appName', application);
+        formData.append('appVersion', version);
+        formData.append('crashType', crashType);
+        formData.append('s3key', s3Key);
+        formData.append('md5', md5);
+
+        if (ipAddress) {
+            const processor = `OBAN-${ipAddress}`;
```
Comment (bobbyg603) [inline src/post/crash-post-client.ts:87]: Let's not append this prefix in code, let's make it so that it's provided in the constructor

File: src/post/crash-post-client.ts [hunk 5]
```diff
@@ -0,0 +1,100 @@
...
+
+export class CrashPostClient {
+
+    private _processorApiClient: BugSplatApiClient;
+    private _s3ApiClient: S3ApiClient;
+
+    constructor(
+        private _database: string,
+        private _environment: Environment = Environment.Node,
+        private _processorIpAddress: string = ''
```
Comment (bobbyg603) [inline src/post/crash-post-client.ts:12]: Add a comment, internal use only

Comment (bobbyg603) [reply src/post/crash-post-client.ts:12]: Rename to processor

File: src/post/crash-post-client.ts [hunk 6]
```diff
@@ -0,0 +1,100 @@
...
+        ipAddress?: string,
+    ): Promise<BugSplatResponse> {
+        const route = '/api/commitS3CrashUpload.php';
+        const formData = this._processorApiClient.createFormData();
+        formData.append('database', database);
+        formData.append('appName', application);
+        formData.append('appVersion', version);
+        formData.append('crashType', crashType);
+        formData.append('s3key', s3Key);
+        formData.append('md5', md5);
```
Comment (bobbyg603) [inline src/post/crash-post-client.ts:84]: Can we get this automatically?

File: spec/files/native/post-native-crash.ts [hunk 7]
```diff
@@ -0,0 +1,35 @@
...
+    authenticatedClient: BugSplatApiClient,
+    database: string,
+    application: string,
+    version: string
+): Promise<number> {
+    const exeFile = createBugSplatFile('./spec/files/native/myConsoleCrasher.exe');
+    const pdbFile = createBugSplatFile('./spec/files/native/myConsoleCrasher.pdb');
+    const files = [exeFile, pdbFile];
+    const symbolsApiClient = new SymbolsApiClient(authenticatedClient);
+    await symbolsApiClient.post(
```
Comment (bobbyg603) [inline spec/files/native/post-native-crash.ts:16]: postSymbols

File: src/post/crash-post-client.e2e.ts [hunk 8]
```diff
@@ -0,0 +1,25 @@
...
+            const crashPostClient = new CrashPostClient(config.database);
+            const result = await crashPostClient.postCrash(
+                application,
+                version,
+                CrashType.native,
+                crashFile,
+                md5
+            );
+
+            expect(result.status).toEqual(200);
```
Comment (bobbyg603) [inline src/post/crash-post-client.e2e.ts:22]: Let's test that we get back an ID greater than 0

File: src/post/crash-post-client.spec.ts [hunk 9]
```diff
@@ -0,0 +1,95 @@
...
+                application,
+                version,
+                type,
+                file,
+                md5
+            );
+        });
+
+        it('should call fetch with getCrashUploadUrl route to get presignedUrl for crash upload', () => {
+            const presignedUrl = `api/getCrashUploadUrl.php?database=${database}&appName=${application}&appVersion=${version}&crashPostSize=${file.size}`;
```
Comment (bobbyg603) [inline src/post/crash-post-client.spec.ts:67]: do we need the php extension on getCrashUploadUrl?

File: src/post/crash-post-client.ts (hunk 2 above)
Comment (bobbyg603) [reply src/post/crash-post-client.ts]: Overkill

**Review by daveplunkett — APPROVED** [review]
